spring:
  application:
    name: currency-exchange
  datasource:
    url: jdbc:postgresql://localhost:5432/d-c
    username: postgres
    password: Qasaqayj7
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka